version: "3.1"

services:
  tgbot:
    container_name: bot
    build:
      context: .
    command: python app.py
    restart: always
    networks:
      - botnet
    environment:
      WEBAPP_PORT: 3001
    env_file:
      - ".env"
    volumes:
     - .:/src
    depends_on:
      - tg-redis

  tg-redis:
    container_name: tg-redis
    image: "redis:6.0.6-alpine"
    networks:
      - botnet
    restart: always
    command: redis-server

networks:
  botnet:
    driver: bridge
